### ISSUE TITLE
RetinaFace.detect() got an unexpected keyword argument 'threshold'

### ISSUE THREAD

**Issue by mrunal2401** [Seanseattle/MobileFaceSwap#21]
Hey, i was using this but got an unexpected error while executing this "python video_test.py --target_video_path video.mp4 --source_img_path demo_face.jpeg --output_path results". I have attached Screenshot for more understanding
![Screenshot 2023-03-03 at 12 34 45 PM](https://user-images.githubusercontent.com/122784951/222654161-1ae749e5-790d-46fc-a4eb-08573cee0f99.png)

**Comment by yanchujian** [comment]
Lightface version is high，try download a low version

**Comment by mrunal2401** [comment]
> Lightface version is high，try download a low version

Okay

**Comment by anleleaaa** [comment]
> Lightface version is high，try download a low version

How much time does this face swap take? Quick, can you send more results of face changing
